#!/bin/bash

echo "welcome to rajashekar"
# this is leader
echo "an IT Infrastructure professional with a strong hands-on background.
You have around 2+ years of experience working across Linux administration, virtualization, and cloud"